export const JOURNAL_ESSAYS = [
  {
    slug: "on-listening-as-a-practice",
    title: "On Listening as a Practice",
    category: "Music · Practice",
    excerpt: "Two years into learning the Bansuri, a workshop changed the way I understood listening — in music and beyond it.",
    paragraphs: [
      "I've spent two years learning how to play the Bansuri.",
      "For most of that time, I thought I was learning music.",
      "I was learning notes. Finger positions. Scales. Songs. Breath. Technique.",
      "I watched carefully. I copied carefully. I tried to reproduce what I had been shown.",
      "Then I went to a workshop with a musician who had been playing for fifty years.",
      "He didn't give us written notes.",
      "He played.",
      "We listened.",
      "Then we tried to play it back.",
      "On the first day, I sat there thinking:",
      "I don't know anything.",
      "The strange part was that I actually knew more than I thought I did. Two years of practice had already put something into my hands. I simply didn't trust it yet.",
      "On the second day, something shifted.",
      "I stopped trying to watch the answer.",
      "I listened.",
      "The ear began to lead instead of the eye.",
      "It sounds like a small distinction. It isn't.",
      "I've started noticing the same thing outside music.",
      "A conversation changes when you stop preparing your response.",
      "A place changes when you stop photographing it long enough to actually see it.",
      "Even the flute tells you immediately when your attention has wandered. It doesn't care what you intended to play. It only responds to what you give it in this breath.",
      "Maybe listening is less about hearing more.",
      "Maybe it is about bringing less noise to what is already there.",
      "I'm still learning.",
      "But increasingly, I think the practice isn't really about playing the right note.",
      "It is about being present enough to hear which note is actually being asked for.",
    ],
  },
  {
    slug: "what-the-land-has-been-teaching-me",
    title: "What the Land Has Been Teaching Me",
    category: "Nature · Stewardship",
    excerpt: "Microgreens, monsoon, and what growing living things is teaching me about time, control, and responsibility.",
    paragraphs: [
      "I used to think of nature as somewhere I went.",
      "Mountains. Forests. Beaches. Rivers.",
      "A destination, a road, a photograph, a memory.",
      "Living in Goa has started changing that.",
      "Here, the rain doesn't feel like weather happening somewhere outside the window. It changes the soil. The roads. The plants. The insects. The work.",
      "Things grow whether I'm paying attention or not.",
      "That has been humbling.",
      "I'm learning microgreens now. Growing something with your hands creates a different relationship with time. You cannot negotiate with germination. You cannot make a plant grow faster because you have somewhere to be.",
      "You prepare the conditions.",
      "Then you wait.",
      "There is something strangely similar about learning music.",
      "You practice. You pay attention. You create the conditions.",
      "And then you accept that growth has its own timing.",
      "The land has also made me notice how much of modern life is built around removing friction.",
      "We want everything predictable. Clean. Fast. Available.",
      "But a living thing isn't like that.",
      "Rain arrives when it arrives.",
      "A seed takes the time it takes.",
      "A road through the jungle doesn't promise you anything.",
      "The more I work with living things, the less interested I become in controlling every outcome.",
      "Perhaps stewardship is not control.",
      "Perhaps it is attention, responsibility and enough humility to understand that you are participating in something you do not completely command.",
      "I'm still learning what that means.",
      "For now, I'm happy to keep my hands in the soil.",
    ],
  },
  {
    slug: "goa-slowly",
    title: "Goa, Slowly",
    category: "Place · A New Chapter",
    excerpt: "Two bags, a flute, and the ordinary work of discovering that a place offers conditions — not answers.",
    paragraphs: [
      "I came to Goa with two bags and a flute.",
      "The plan sounded simple enough.",
      "Build something. Teach music. Grow things. Stay near the sea.",
      "Life, as usual, had other ideas.",
      "The first thing I noticed wasn't the beach.",
      "It was the green.",
      "The roads felt different. Trees crowded the edges. Tropical plants grew everywhere. Beyond them were hills, jungle and, eventually, the Arabian Sea.",
      "On the first morning I woke early and listened.",
      "Birds.",
      "Insects.",
      "Leaves moving.",
      "A sound somewhere that I couldn't identify.",
      "It reminded me of something I had been learning through the flute: the world is already making music. You don't always need to add anything.",
      "Goa has been teaching me that slowly.",
      "Not through some dramatic transformation.",
      "Through ordinary mornings.",
      "Through rain.",
      "Through getting things wrong.",
      "Through teaching students.",
      "Through carrying things, cleaning things, growing things, fixing things.",
      "Through sitting with the flute when I don't particularly feel like practising.",
      "I think I arrived wanting Goa to change my life.",
      "Now I'm beginning to understand that a place doesn't really do that.",
      "It gives you conditions.",
      "You still have to change.",
      "And perhaps that is why I'm here.",
      "Not because I have found the answer.",
      "Because I finally have enough quiet to keep asking the question.",
    ],
  },
] as const;

export function getJournalEssay(slug: string) {
  return JOURNAL_ESSAYS.find((essay) => essay.slug === slug);
}